ALTER TABLE settings ADD COLUMN IF NOT EXISTS hyp_enabled BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS hyp_masof VARCHAR(20);
ALTER TABLE settings ADD COLUMN IF NOT EXISTS hyp_key VARCHAR(255);
ALTER TABLE settings ADD COLUMN IF NOT EXISTS hyp_passp VARCHAR(255);
